"""
Lesson 01: Message Types in LLM Applications
=============================================

This module covers the fundamental message types used in LangChain
for interacting with Large Language Models (LLMs).
"""

# ============================================================================
# MESSAGE TYPES
# ============================================================================
# 
# LangChain uses different message types to structure communication with LLMs:
#
# 1. System Message
#    - Sets the behavior and context for the AI assistant
#    - Defines the AI's role, tone, and instructions
#    - Example: "You are a helpful Python coding assistant"
#
# 2. Human Message
#    - Represents user input or questions
#    - The actual query or request from the user
#    - Example: "How do I sort a list in Python?"
#
# 3. AI Message
#    - Represents responses generated by the AI model
#    - The output from the language model
#    - Example: "You can use the sort() method or sorted() function"
#
# ============================================================================
# PROMPT CONSTRUCTION
# ============================================================================
#
# A complete prompt is constructed by combining:
#
#   PROMPT = System Message + Human Message
#
# The system message provides context and instructions, while the human
# message contains the actual user query. Together, they form the complete
# prompt sent to the LLM for processing.

# ============================================================================
# MESSAGE STATEFULNESS
# ============================================================================
#
# IMPORTANT: LLM Messages are STATELESS
#
# Key Points:
#   - Messages do NOT have memory of previous interactions
#   - Each message is completely independent
#   - No information is retained from previous messages
#   - Each interaction starts fresh without context
#
# Maintaining Context Across Interactions:
#   To keep context across multiple interactions, you have two options:
#
#   1. Include relevant information in each new message
#      - Repeat necessary context in every request
#      - Ensures the LLM has the information it needs
#
#   2. Use a Conversation History
#      - Maintain a list of all previous messages
#      - Pass the entire history with each new request
#      - Allows the LLM to understand the full conversation thread
#
# Example:
#   First message: "My name is John"
#   Second message: "What is my name?" <- LLM won't know unless you include history!
#   Solution: Include first message in history when sending second message

# ============================================================================
# CODE EXAMPLES
# ============================================================================

# Example 1: Using System and Human Messages
# -------------------------------------------
from langchain_ollama import OllamaLLM
from langchain_core.messages import SystemMessage, HumanMessage

# Initialize the Ollama model
llm = OllamaLLM(model="gemma3:1b")

# Create a system message to define the AI's role
system_message = SystemMessage(
    content="You are a helpful Python programming assistant. Provide clear and concise answers."
)

# Create a human message with the user's question
human_message = HumanMessage(
    content="How do I sort a list in Python?"
)

# Combine messages and send to LLM
messages = [system_message, human_message]
response = llm.invoke(messages)
print("Response:", response)


# Example 2: Maintaining Context with Conversation History
# ---------------------------------------------------------
from langchain_core.messages import AIMessage

# First interaction
print("\n--- First Interaction ---")
conversation_history = []

system_msg = SystemMessage(content="You are a helpful assistant.")
human_msg_1 = HumanMessage(content="My name is Alice and I work as a software engineer.")

conversation_history.append(system_msg)
conversation_history.append(human_msg_1)

response_1 = llm.invoke(conversation_history)
print("User:", human_msg_1.content)
print("AI:", response_1)

# Add AI response to history
conversation_history.append(AIMessage(content=response_1))


# Second interaction - using conversation history to maintain context
print("\n--- Second Interaction ---")
human_msg_2 = HumanMessage(content="What programming languages should I learn?")

conversation_history.append(human_msg_2)
response_2 = llm.invoke(conversation_history)
print("User:", human_msg_2.content)
print("AI:", response_2)

# Add AI response to history
conversation_history.append(AIMessage(content=response_2))


# Example 3: Without Conversation History (Stateless - Context Lost)
# ------------------------------------------------------------------
print("\n--- Without Conversation History (Context Lost) ---")
human_msg_3 = HumanMessage(content="What's my name?")

# Without history, the LLM won't remember the name from earlier
response_3_no_history = llm.invoke([human_msg_3])
print("Without history - User:", human_msg_3.content)
print("Without history - AI:", response_3_no_history)
print("^ Notice: The LLM doesn't know the name 'Alice'!\n")


# Example 4: With Conversation History (Context Maintained)
# ---------------------------------------------------------
print("--- With Conversation History (Context Maintained) ---")
# Using the full conversation_history from before
response_3_with_history = llm.invoke(conversation_history + [human_msg_3])
print("With history - User:", human_msg_3.content)
print("With history - AI:", response_3_with_history)
print("^ Notice: The LLM remembers that your name is 'Alice'!")